

def zigzag(bloc):
    bloc1D = []
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][1])
    bloc1D.append(bloc[1][0])
    bloc1D.append(bloc[2][0])
    bloc1D.append(bloc[1][1])
    bloc1D.append(bloc[0][2])
    bloc1D.append(bloc[0][3])
    bloc1D.append(bloc[1][2])
    bloc1D.append(bloc[2][1])
    bloc1D.append(bloc[3][0])

    bloc1D.append(bloc[4][0])
    bloc1D.append(bloc[3][1])
    bloc1D.append(bloc[2][2])
    bloc1D.append(bloc[1][3])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])

    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])

    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])

    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])

    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])

    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])
    bloc1D.append(bloc[0][0])